### PR TITLE
Remove test route.

### LINKED ISSUE #22: Remove test route
Now that we have test routes, for all roles, we don't need the initial test route anymore.

https://github.com/JefvdA/Chat-app-BE/blob/5482b76cdd409a00e0a1e0de4702046a7a104a71/index.js#L36-L39

### PR DESCRIPTION
**Pull request by ali139713**
Fixes #22

### CODE REVIEW

**Review by JefvdA — CHANGES_REQUESTED** [review]
Hey, thanks for looking at this project.

I probably should have explained better, but I just wanted the "/api/" route gone.
https://github.com/JefvdA/Chat-app-BE/blob/5482b76cdd409a00e0a1e0de4702046a7a104a71/index.js#L36-L39

The other "test routes" that were found in the file you removed were still used to test authorization.

Sorry for the confusion, but could you just remove the "/api/ test route which i mentioned above? And unremove the "test.routes.js" file? Thanks

**Comment by ali139713** [comment]
Sure

**Review by JefvdA — APPROVED** [review]
:+1: Again, sorry for the confusing issue.

**Comment by ali139713** [comment]
Thanks👍🏻

**Pull request merged**
